[project]
name="fraud-feature-engineering"
version="0.1.0"
requires-python=">=3.12"
authors=[
    {name="Gabriel Meirinho", email="gsilva.meirinho@gmail.com"}
]
dependencies = [
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.6",
    "numpy>=2.2.6",
    "pandas>=2.3.1",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
]

